spring:
  datasource:
    url: jdbc:mysql://43.143.45.182:3306/springsecurity?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: xiaoyong66
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 43.143.45.182
    password: xiaoyong66